name: Teesas Api Autodeployment

on:
  push:
    branches:
        - staging

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build
        env: 
          CI: true   


  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}
          script: |
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
              . ~/.nvm/nvm.sh
              nvm install --lts
              npm install -g pm2
              mkdir cicd && cd cicd
              git pull origin staging
              npm install
              npm run build
              npm run stop
              npm run start
               
              # pm2 restart api
